const cart = {
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  REDUCE_SUCCESS: "REDUCE_SUCCESS",
  INCREASE_SUCCESS: "INCREASE_SUCCESS",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  ORDER_SUCCESS: "ORDER_SUCCESS"
}

export default cart;
