const product = {
  GET_FLASH_SALE_SUCCESS: "GET_FLASH_SALE_SUCCESS",
  GET_ALL_PRODUCTS_SELLER_SUCCESS: "GET_ALL_PRODUCTS_SELLER_SUCCESS",
  ADD_PRODUCT_SUCCEES: "ADD_PRODUCT_SUCCEES"
}

export default product;
