export const signup = {
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};

export const signin = {
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_WITH_GOOGLE_SUCCESS: "SIGNIN_WITH_GOOGLE_SUCCESS",
  SIGNIN_WITH_FACEBOOK_SUCCESS: "SIGNIN_WITH_FACEBOOK_SUCCESS",
};

export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";

export const LOADING = "LOADING";

export const LOAD_END = "LOAD_END";

export const SIGNED_OUT = "SIGNED_OUT";

export const profile = {
  UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS"
}